---
- hosts: localhost
  tasks:       
  - name: check package already exists
    shell:
      cmd: ls $HOME | grep hello-world-0.0.1.deb
    register: deb_package_check
    failed_when: deb_package_check.rc > 1
    changed_when: deb_package_check.stdout == ""

  - name: fetch package
    get_url:
      url: https://eedorenko.github.io/kalypso-oci-app-src/hello-world-0.0.1.deb
      dest: $HOME/hello-world-0.0.1.deb
    when: deb_package_check.changed

  - name: install application
    shell: |
      dpkg -x $HOME/hello-world-0.0.1.deb $HOME
      pkill sample
      PORT=8080 $HOME/usr/bin/sample &

