---
- hosts: localhost
  tasks:       
  - name: check package already exists
    shell:
      cmd: ls | grep hello-world-0.0.1.deb
    register: deb_package_check
    failed_when: deb_package_check.rc > 1
    changed_when: deb_package_check.stdout == ""

  - name: fetch package
    get_url:
      url: https://eedorenko.github.io/kalypso-oci-app-src/hello-world-0.0.1.deb
      dest: ./hello-world-0.0.1.deb
    when: deb_package_check.stdout == ""

  - name: install application
    shell: |
      dpkg -x ./hello-world-0.0.1.deb .
      pkill sample
      PORT=8080 ./usr/bin/sample &
    # when: deb_package_check.stdout == ""      

